Probandonosaa

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,28 +10,26 @@ on:
     branches:
       - develop
       - main
+
 jobs:
-  distribute:
+  build-and-distribute:
     runs-on: ubuntu-latest
     steps:
       # Checkout the repository
       - name: Checkout code
         uses: actions/checkout@v3
 
-      # Download APK from direct URL
-      - name: Download APK
-        run: |
-          APK_URL="https://expo.dev/artifacts/eas/wdY1ZbFjJ5QFc5EGTZTQNx.apk"
-          echo "Downloading APK from $APK_URL"
-          curl -o app-release.apk "$APK_URL"
-
-      # Upload APK as an artifact
-      - name: Upload APK artifact
-        uses: actions/upload-artifact@v3
+      # Set up Node.js
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
         with:
-          name: android-apk
-          path: app-release.apk
+          node-version: 18
 
+      # Install dependencies
+      - name: Install Firebase CLI
+        run: npm install -g firebase-tools
+
+      # Distribute APK to Firebase App Distribution
       - name: Upload APK to Firebase App Distribution
         env:
           GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-credentials.json
@@ -39,10 +37,13 @@ jobs:
           # Escribe las credenciales en un archivo
           echo "${{ secrets.FIREBASE_CREDENTIALS }}" > $HOME/firebase-credentials.json
 
-          # Verifica si el archivo se generó correctamente (opcional, para depuración)
-          cat $HOME/firebase-credentials.json
+          # Verifica si el archivo APK existe
+          if [ ! -f app-release.apk ]; then
+            echo "Error: APK no encontrado en app-release.apk"
+            exit 1
+          fi
 
-          # Distribuye el APK con Firebase CLI
+          # Distribuye el APK
           firebase appdistribution:distribute app-release.apk \
             --app "1:410686902807:android:c74035158ef816ac528252" \
             --groups "testers-group" \
